'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Check, ClipboardList, Fuel, Menu, Package, Send, Truck, UserRound } from 'lucide-react'

const modules = [{ label: 'Yakıt girişi', detail: 'Dolum, litre ve araç bilgisi', icon: Fuel }, { label: 'Üretim kaydı', detail: 'Üretim miktarı ve sevkiyat', icon: ClipboardList }, { label: 'Araç durumu', detail: 'Kilometre ve arıza bildirimi', icon: Truck }, { label: 'Depo sayımı', detail: 'Stok hareketi ve kritik seviye', icon: Package }]
type QueuedRecord = { id: string; resource: string; payload: Record<string, string> }
function openQueueDb() { return new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open('zirveflow-field', 1); request.onupgradeneeded = () => request.result.createObjectStore('queue', { keyPath: 'id' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) }) }
async function readQueue(): Promise<QueuedRecord[]> { const db = await openQueueDb(); return new Promise((resolve, reject) => { const request = db.transaction('queue', 'readonly').objectStore('queue').getAll(); request.onsuccess = () => resolve(request.result as QueuedRecord[]); request.onerror = () => reject(request.error) }) }
async function enqueue(record: QueuedRecord) { const db = await openQueueDb(); return new Promise<void>((resolve, reject) => { const request = db.transaction('queue', 'readwrite').objectStore('queue').put(record); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error) }) }
async function removeQueued(id: string) { const db = await openQueueDb(); return new Promise<void>((resolve, reject) => { const request = db.transaction('queue', 'readwrite').objectStore('queue').delete(id); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error) }) }

export default function FieldPage() {
  const [active, setActive] = useState('Yakıt girişi')
  const [saved, setSaved] = useState(false)
  const [userName, setUserName] = useState('Aktif kullanıcı')
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10))
  const [value, setValue] = useState('')
  const [identifier, setIdentifier] = useState('')
  const [attachment, setAttachment] = useState<File | null>(null)
  const [saving, setSaving] = useState(false)
  const [online, setOnline] = useState(true)
  const [queuedCount, setQueuedCount] = useState(0)
  const [error, setError] = useState('')
  const [sessionChecked, setSessionChecked] = useState(false)
  const [authenticated, setAuthenticated] = useState(false)
  useEffect(() => { const syncQueue = async () => { if (!navigator.onLine) return; const queued = await readQueue().catch(() => []); for (const item of queued) { const response = await fetch(`/api/business?resource=${item.resource}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(item.payload) }).catch(() => null); if (response?.ok) await removeQueued(item.id) }; setQueuedCount((await readQueue().catch(() => [])).length) }; const updateOnline = () => { setOnline(navigator.onLine); if (navigator.onLine) void syncQueue() }; updateOnline(); void readQueue().then(items => setQueuedCount(items.length)).catch(() => {}); window.addEventListener('online', updateOnline); window.addEventListener('offline', updateOnline); fetch('/api/auth/get-session').then(response => response.ok ? response.json() : null).then(data => { if (data?.user) { setAuthenticated(true); if (data.user.name) setUserName(data.user.name) } }).catch(() => {}).finally(() => setSessionChecked(true)); return () => { window.removeEventListener('online', updateOnline); window.removeEventListener('offline', updateOnline) } }, [])
  if (sessionChecked && !authenticated) return <main className="field-page field-auth-required"><section className="field-form"><span className="eyebrow">Saha uygulaması</span><h1>Oturum gerekli</h1><p>Saha kayıtlarını göndermek için hesabınızla giriş yapın.</p><Link className="field-submit" href="/sign-in">Giriş yap</Link></section></main>
  const submit = async () => { if (!value.trim()) { setError('Lütfen kayıt bilgisini girin.'); return }; setSaving(true); setError(''); const resource = active === 'Yakıt girişi' ? 'fuel' : active === 'Üretim kaydı' ? 'production' : active === 'Araç durumu' ? 'faults' : 'assets'; try { let attachmentPathname = ''; if (attachment) { const upload = new FormData(); upload.append('file', attachment); const uploadResponse = await fetch('/api/field/upload', { method: 'POST', body: upload }); if (!uploadResponse.ok) { const uploadError = await uploadResponse.json().catch(() => null); throw new Error(uploadError?.error || 'Dosya yüklenemedi') }; attachmentPathname = (await uploadResponse.json()).pathname } const payload = { date, identifier: identifier.trim(), value: value.trim(), module: active, source: 'field', attachmentPathname }; if (!online) { await enqueue({ id: crypto.randomUUID(), resource, payload }); setQueuedCount(count => count + 1); setSaved(true); setError('Bağlantı yok. Kayıt cihazda güvenle bekletiliyor; bağlantı gelince gönderilecek.'); setValue(''); setIdentifier(''); setAttachment(null); return }; const response = await fetch(`/api/business?resource=${resource}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(); setSaved(true); setValue(''); setIdentifier(''); setAttachment(null) } catch { setError('Kayıt gönderilemedi. Yetkinizi veya bağlantınızı kontrol edin.') } finally { setSaving(false) } }
  return <main className="field-page"><header className="field-topbar"><div className="field-brand"><div className="field-mark">m</div><div><strong>madenova</strong><span>Saha uygulaması</span></div></div><button className="field-user" aria-label="Kullanıcı menüsü"><UserRound size={18}/></button></header><section className="field-hero"><span className="eyebrow">Bugünkü saha işleri</span><h1>Merhaba, {userName}</h1><p>Kaydınızı girin; yöneticiniz veriyi ana panelde anlık görür.</p><div className="sync-pill"><span className={online ? '' : 'offline-dot'}/> {online ? 'Sunucu ile senkronize' : 'Çevrimdışı'}{queuedCount > 0 && ` · ${queuedCount} bekleyen kayıt`}</div></section><nav className="field-modules" aria-label="Saha modülleri">{modules.map(({ label, detail, icon: Icon }) => <button key={label} className={active === label ? 'selected' : ''} onClick={() => { setActive(label); setSaved(false) }}><Icon size={19}/><span><strong>{label}</strong><small>{detail}</small></span></button>)}</nav><section className="field-form"><div className="field-form-heading"><div><span className="eyebrow">Yeni kayıt</span><h2>{active}</h2></div><span className="actor-chip"><UserRound size={13}/> Aktif kullanıcı</span></div><label>İşlem tarihi<input type="date" value={date} onChange={event => setDate(event.target.value)}/></label><label>{active === 'Yakıt girişi' ? 'Araç plakası' : active === 'Üretim kaydı' ? 'Ürün / malzeme' : active === 'Araç durumu' ? 'Araç plakası' : 'Stok kalemi'}<input value={identifier} onChange={event => setIdentifier(event.target.value)} placeholder="Bilgi girin"/></label><label>Miktar / açıklama<input value={value} onChange={event => setValue(event.target.value)} placeholder="Örn. 250 litre veya kısa açıklama"/></label><label>Fotoğraf veya belge<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={event => setAttachment(event.target.files?.[0] || null)}/>{attachment && <small>{attachment.name}</small>}</label>{error && <p className="field-error">{error}</p>}<button className="field-submit" disabled={saving} onClick={submit}>{saved ? <><Check size={17}/> Kaydedildi ve senkronlandı</> : <><Send size={17}/> {saving ? 'Gönderiliyor...' : 'Kaydı gönder'}</>}</button>{saved && <p className="field-confirm">Kayıt zaman damgası ve kullanıcı bilgisiyle yönetici paneline aktarıldı.</p>}</section><footer className="field-footer"><Menu size={17}/> Yetkili olduğunuz modülleri görüyorsunuz · Veriler güvenli sunucuda saklanır</footer></main>
}
