'use client'

import { useState } from 'react'
import { Check, ClipboardList, Fuel, Menu, Package, Send, Truck, UserRound } from 'lucide-react'

const modules = [{ label: 'Yakıt girişi', detail: 'Dolum, litre ve araç bilgisi', icon: Fuel }, { label: 'Üretim kaydı', detail: 'Üretim miktarı ve sevkiyat', icon: ClipboardList }, { label: 'Araç durumu', detail: 'Kilometre ve arıza bildirimi', icon: Truck }, { label: 'Depo sayımı', detail: 'Stok hareketi ve kritik seviye', icon: Package }]

export default function FieldPage() {
  const [active, setActive] = useState('Yakıt girişi')
  const [saved, setSaved] = useState(false)
  return <main className="field-page"><header className="field-topbar"><div className="field-brand"><div className="field-mark">z</div><div><strong>zirveflow</strong><span>Saha uygulaması</span></div></div><button className="field-user" aria-label="Kullanıcı menüsü"><UserRound size={18}/></button></header><section className="field-hero"><span className="eyebrow">Bugünkü saha işleri</span><h1>Merhaba, Emre</h1><p>Kaydınızı girin; yöneticiniz veriyi ana panelde anlık görür.</p><div className="sync-pill"><span/> Sunucu ile senkronize</div></section><nav className="field-modules" aria-label="Saha modülleri">{modules.map(({ label, detail, icon: Icon }) => <button key={label} className={active === label ? 'selected' : ''} onClick={() => { setActive(label); setSaved(false) }}><Icon size={19}/><span><strong>{label}</strong><small>{detail}</small></span></button>)}</nav><section className="field-form"><div className="field-form-heading"><div><span className="eyebrow">Yeni kayıt</span><h2>{active}</h2></div><span className="actor-chip"><UserRound size={13}/> Emre Yılmaz</span></div><label>İşlem tarihi<input type="date" defaultValue={new Date().toISOString().slice(0, 10)}/></label><label>{active === 'Yakıt girişi' ? 'Araç plakası' : active === 'Üretim kaydı' ? 'Ürün / malzeme' : active === 'Araç durumu' ? 'Araç plakası' : 'Stok kalemi'}<input placeholder="Bilgi girin"/></label><label>Miktar / açıklama<input placeholder="Örn. 250 litre veya kısa açıklama"/></label><button className="field-submit" onClick={() => setSaved(true)}>{saved ? <><Check size={17}/> Kaydedildi ve senkronlandı</> : <><Send size={17}/> Kaydı gönder</>}</button>{saved && <p className="field-confirm">Kayıt zaman damgası ve kullanıcı bilgisiyle yönetici paneline aktarıldı.</p>}</section><footer className="field-footer"><Menu size={17}/> Yetkili olduğunuz modülleri görüyorsunuz · Veriler güvenli sunucuda saklanır</footer></main>
}
