import { NextResponse } from 'next/server'
import { headers } from 'next/headers'
import { Pool } from 'pg'
import { auth } from '@/lib/auth'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
let catalogSchemaReady: Promise<void> | null = null
async function ensureCatalogSchema() { catalogSchemaReady ??= pool.query(`CREATE TABLE IF NOT EXISTS zirveflow_product_catalog (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL, code TEXT NOT NULL, name TEXT NOT NULL, category TEXT NOT NULL, unit TEXT NOT NULL, minimum NUMERIC NOT NULL DEFAULT 0, description TEXT NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id, code))`).then(() => undefined); await catalogSchemaReady }
const allowedTables = { sites: 'zirveflow_sites', production: 'zirveflow_production', workers: 'zirveflow_workers', warehouse: 'zirveflow_warehouse_items', faults: 'zirveflow_vehicle_faults' } as const

type Resource = keyof typeof allowedTables
async function getUserId() {
  const session = await auth.api.getSession({ headers: await headers() })
  return session?.user?.id ?? null
}
function getResource(request: Request): Resource | null { const value = new URL(request.url).searchParams.get('resource'); return value && value in allowedTables ? value as Resource : null }
export async function GET(request: Request) { const userId = await getUserId(); if (!userId) return NextResponse.json({ error: 'Oturum gerekli' }, { status: 401 }); if (new URL(request.url).searchParams.get('resource') === 'catalog') { await ensureCatalogSchema(); const result = await pool.query('SELECT * FROM zirveflow_product_catalog WHERE user_id = $1 ORDER BY code ASC', [userId]); return NextResponse.json(result.rows) } const resource = getResource(request); if (!resource) return NextResponse.json({ error: 'Geçersiz kaynak' }, { status: 400 }); const table = allowedTables[resource]; const result = await pool.query(`SELECT * FROM ${table} WHERE user_id = $1 ORDER BY created_at DESC`, [userId]); return NextResponse.json(result.rows) }
export async function POST(request: Request) { const userId = await getUserId(); if (!userId) return NextResponse.json({ error: 'Oturum gerekli' }, { status: 401 }); if (new URL(request.url).searchParams.get('resource') === 'catalog') { await ensureCatalogSchema(); const body = await request.json() as { code?: string; name?: string; category?: string; unit?: string; minimum?: number; description?: string }; if (!body.code || !body.name || !body.category || !body.unit) return NextResponse.json({ error: 'Ürün kodu, ad, kategori ve birim zorunludur.' }, { status: 400 }); const result = await pool.query('INSERT INTO zirveflow_product_catalog (user_id, code, name, category, unit, minimum, description) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *', [userId, body.code.trim().toUpperCase(), body.name.trim(), body.category, body.unit, Math.max(0, Number(body.minimum || 0)), body.description?.trim() || '']); return NextResponse.json(result.rows[0], { status: 201 }) } const resource = getResource(request); if (!resource) return NextResponse.json({ error: 'Geçersiz kaynak' }, { status: 400 }); const body = await request.json(); const table = allowedTables[resource]; const fields = Object.keys(body).filter(key => /^[a-z_]+$/.test(key) && !['id','user_id','created_at'].includes(key)); if (!fields.length) return NextResponse.json({ error: 'Kayıt alanı gerekli' }, { status: 400 }); const values = fields.map(field => body[field]); const placeholders = fields.map((_, index) => `$${index + 2}`).join(', '); const result = await pool.query(`INSERT INTO ${table} (user_id, ${fields.join(', ')}) VALUES ($1, ${placeholders}) RETURNING *`, [userId, ...values]); return NextResponse.json(result.rows[0], { status: 201 }) }
export async function PUT(request: Request) { const userId = await getUserId(); if (!userId) return NextResponse.json({ error: 'Oturum gerekli' }, { status: 401 }); const resource = getResource(request); const id = new URL(request.url).searchParams.get('id'); if (!resource || !id) return NextResponse.json({ error: 'Kaynak ve id gerekli' }, { status: 400 }); const body = await request.json(); const fields = Object.keys(body).filter(key => /^[a-z_]+$/.test(key) && !['id','user_id','created_at'].includes(key)); if (!fields.length) return NextResponse.json({ error: 'Güncellenecek alan gerekli' }, { status: 400 }); const values = fields.map(field => body[field]); const assignments = fields.map((field, index) => `${field} = $${index + 3}`).join(', '); const result = await pool.query(`UPDATE ${allowedTables[resource]} SET ${assignments} WHERE id = $1 AND user_id = $2 RETURNING *`, [id, userId, ...values]); if (!result.rowCount) return NextResponse.json({ error: 'Kayıt bulunamadı' }, { status: 404 }); return NextResponse.json(result.rows[0]) }
export async function DELETE(request: Request) { const userId = await getUserId(); if (!userId) return NextResponse.json({ error: 'Oturum gerekli' }, { status: 401 }); const resource = getResource(request); const id = new URL(request.url).searchParams.get('id'); if (!resource || !id) return NextResponse.json({ error: 'Kaynak ve id gerekli' }, { status: 400 }); const result = await pool.query(`DELETE FROM ${allowedTables[resource]} WHERE id = $1 AND user_id = $2`, [id, userId]); if (!result.rowCount) return NextResponse.json({ error: 'Kayıt bulunamadı' }, { status: 404 }); return NextResponse.json({ ok: true }) }
