'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Check, CircleAlert, ExternalLink, KeyRound, Loader2, RefreshCw, ShieldCheck, Wifi } from 'lucide-react'

type Provider = { id: string; category: string; name: string; description: string; configured: boolean; enabled: boolean; testedAt: string | null; testStatus: string | null; variables: Array<{ key: string; configured: boolean }> }

export default function ProviderSettingsPage() {
  const [providers, setProviders] = useState<Provider[]>([])
  const [loading, setLoading] = useState(true)
  const [message, setMessage] = useState('')
  const [mapsEnabled, setMapsEnabled] = useState(false)
  const [mapsApiConfigured, setMapsApiConfigured] = useState(false)
  const [mapsSaving, setMapsSaving] = useState(false)
  async function readJson(response: Response) { const text = await response.text(); if (!text) return {}; try { return JSON.parse(text) as Record<string, unknown> } catch { return {} } }
  async function load() { setLoading(true); try { const [response, mapsResponse] = await Promise.all([fetch('/api/settings/providers', { cache: 'no-store' }), fetch('/api/settings/maps', { cache: 'no-store' })]); const data = await readJson(response); const mapsData = await readJson(mapsResponse); if (response.ok && Array.isArray(data.providers)) setProviders(data.providers as Provider[]); else if (!response.ok) setMessage(typeof data.error === 'string' ? data.error : 'Ayarlar yüklenemedi.'); if (mapsResponse.ok) { setMapsEnabled(mapsData.enabled === true); setMapsApiConfigured(mapsData.apiConfigured === true) } else if (mapsResponse.status !== 403) setMessage(typeof mapsData.error === 'string' ? mapsData.error : 'Harita ayarı yüklenemedi.') } catch { setMessage('Ayar bağlantısı kurulamadı. Lütfen tekrar deneyin.') } finally { setLoading(false) } }
  async function toggleMaps() { setMapsSaving(true); try { const response = await fetch('/api/settings/maps', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ enabled: !mapsEnabled }) }); const data = await readJson(response); if (response.ok) { setMapsEnabled(data.enabled === true); setMessage(data.enabled ? 'Google Maps işletme için etkinleştirildi.' : 'Google Maps pasif hale getirildi.') } else setMessage(typeof data.error === 'string' ? data.error : 'Harita ayarı kaydedilemedi.') } catch { setMessage('Harita ayarı kaydedilemedi. Lütfen tekrar deneyin.') } finally { setMapsSaving(false) } }
  async function toggleProvider(provider: Provider) { const response = await fetch('/api/settings/providers', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ providerId: provider.id, enabled: !provider.enabled }) }); const data = await readJson(response); if (!response.ok) { setMessage(typeof data.error === 'string' ? data.error : 'Sağlayıcı ayarı kaydedilemedi.'); return } setProviders((items) => items.map((item) => item.id === provider.id ? { ...item, enabled: data.enabled === true } : item)); setMessage(`${provider.name} ${data.enabled ? 'etkinleştirildi' : 'pasifleştirildi'}.`) }
  async function testProvider(provider: Provider) { const response = await fetch('/api/settings/providers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ providerId: provider.id }) }); const data = await readJson(response); setMessage(typeof data.message === 'string' ? data.message : typeof data.error === 'string' ? data.error : 'Bağlantı testi tamamlandı.'); await load() }
  useEffect(() => { void load() }, [])
  const configuredCount = providers.filter((provider) => provider.configured).length
  return <main className="provider-page"><header className="provider-header"><Link href="/" className="back-link"><ArrowLeft size={16} /> Ana panele dön</Link><div className="provider-title"><div className="provider-title-icon"><KeyRound size={22} /></div><div><span className="eyebrow">Sistem ayarları</span><h1>Sağlayıcılar ve API bağlantıları</h1><p>Uygulamanın kullandığı servisleri güvenli şekilde kontrol edin.</p></div></div><div className="provider-security"><ShieldCheck size={17} /><span>Gizli anahtarlar uygulamaya kaydedilmez; yalnızca sunucu ortamında tutulur.</span></div></header><section className="provider-summary"><div><strong>{configuredCount}/{providers.length}</strong><span>sağlayıcı hazır</span></div><div><strong>{providers.reduce((total, provider) => total + provider.variables.filter((variable) => variable.configured).length, 0)}</strong><span>tanımlı değişken</span></div><button className="secondary-action" onClick={() => void load()}><RefreshCw size={15} /> Yenile</button></section>{message && <div className="provider-message"><CircleAlert size={16} />{message}</div>}{loading ? <div className="provider-loading"><Loader2 className="spin" size={20} /> Bağlantılar kontrol ediliyor...</div> : <section className="provider-grid">{providers.map((provider) => <article className="provider-card" key={provider.id}><div className="provider-card-top"><div><span className="provider-category">{provider.category}</span><h2>{provider.name}</h2></div><span className={`provider-status ${provider.configured ? 'ready' : ''}`}>{provider.configured ? <><Check size={13} /> Hazır</> : <><CircleAlert size={13} /> Eksik</>}</span></div><p>{provider.description}</p><div className="provider-vars">{provider.variables.map((variable) => <div className="provider-var" key={variable.key}><code>{variable.key}</code><span>{variable.configured ? 'Tanımlı' : 'Eksik'}</span></div>)}</div><div className="provider-feature-toggle"><div><strong>İşletmede kullan</strong><small>{provider.enabled ? 'Bu modül aktif.' : 'Pasifken uygulama fallback davranışını korur.'}</small></div><button className={`toggle-switch ${provider.enabled ? 'on' : ''}`} type="button" role="switch" aria-checked={provider.enabled} disabled={!provider.configured} onClick={() => void toggleProvider(provider)}><span /></button></div><div className="provider-card-foot"><span>{provider.testedAt ? `Son test: ${new Date(provider.testedAt).toLocaleString('tr-TR')}` : 'Henüz test edilmedi'}</span><button className="text-link" type="button" onClick={() => void testProvider(provider)}><Wifi size={13} /> Bağlantıyı test et</button></div><div className="provider-card-foot"><span><Wifi size={14} /> Sunucu tarafı bağlantı</span><button className="text-link" onClick={() => setMessage(`${provider.name} için değişkenleri Vercel proje ayarlarının Vars bölümünden tanımlayın.`)}>Kurulum bilgisi <ExternalLink size={13} /></button></div></article>)}</section>}</main>
}
