'use client'

import { useEffect, useState } from 'react'
import { AlertTriangle, ArrowUpRight, BarChart3, BellRing, Boxes, CalendarClock, CheckCircle2, CircleDollarSign, ClipboardCheck, FileWarning, Fuel, Gauge, ShieldAlert, Truck, Users, Wrench } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

type ControlCenterProps = { onOpen: (module: string) => void }

const activity = [
  { title: 'Kontrol merkezi hazır', detail: 'Gerçek kayıtlar eklendikçe KPI ve grafikler güncellenecek.', icon: CheckCircle2, tone: 'ok' },
  { title: 'Bakım planı bekliyor', detail: 'Varlıklar bölümünden ilk bakım planını oluşturun.', icon: Wrench, tone: 'warn' },
  { title: 'Çalışan belgeleri', detail: 'SGK, sağlık ve ehliyet kayıtlarını tamamlayın.', icon: FileWarning, tone: 'info' },
]

const trend = [{ name: 'Pzt', value: 0 }, { name: 'Sal', value: 0 }, { name: 'Çar', value: 0 }, { name: 'Per', value: 0 }, { name: 'Cum', value: 0 }, { name: 'Cmt', value: 0 }, { name: 'Paz', value: 0 }]
const distribution = [{ name: 'Operasyon', value: 1, color: '#087f78' }, { name: 'Bakım', value: 1, color: '#d7874c' }, { name: 'Finans', value: 1, color: '#8aa5a5' }]

export function ControlCenter({ onOpen }: ControlCenterProps) {
  const [counts, setCounts] = useState<Record<string, number>>({})
  useEffect(() => { let cancelled = false; fetch('/api/business?resource=summary').then(response => response.ok ? response.json() : { counts: {} }).then(data => { if (!cancelled) setCounts(data.counts || {}) }).catch(() => undefined); return () => { cancelled = true } }, [])
  const active = (key: string) => Number(counts[key] || 0)
  const [online, setOnline] = useState(true)
  useEffect(() => { const update = () => setOnline(navigator.onLine); update(); window.addEventListener('online', update); window.addEventListener('offline', update); return () => { window.removeEventListener('online', update); window.removeEventListener('offline', update) } }, [])
  return <div className="control-center page-wrap">
    <div className="page-heading control-heading"><div><p className="eyebrow">İşletme kontrol merkezi <span className={`connection-pill ${online ? 'online' : 'offline'}`}><i/> {online ? 'Bağlı' : 'Çevrimdışı'}</span></p><h1>Bugün işletmenizde</h1><p className="muted">Operasyon, varlık, ekip, finans ve uyum süreçlerini tek ekrandan yönetin.</p></div><button className="primary-button" onClick={() => onOpen('Raporlar')}><BarChart3 size={17}/> Rapor merkezine git</button></div>
    <div className="control-kpis"><button onClick={() => onOpen('Üretim & Sevkiyat')}><Gauge/><strong>{active('production')}</strong><span>Üretim kayıtları</span><small>Veri bekleniyor <ArrowUpRight size={12}/></small></button><button onClick={() => onOpen('Araç Arızaları')}><Wrench/><strong>{active('maintenance') + active('faults')}</strong><span>Bakım / arıza kaydı</span><small>Plan ekle <ArrowUpRight size={12}/></small></button><button onClick={() => onOpen('Stoklar')}><Boxes/><strong>{active('stock')}</strong><span>Stok kayıtları</span><small>Stokları incele <ArrowUpRight size={12}/></small></button><button onClick={() => onOpen('Tahsilat / Ödeme')}><CircleDollarSign/><strong>{active('finance')}</strong><span>Finans hareketi</span><small>Finansa git <ArrowUpRight size={12}/></small></button></div>
    <div className="control-grid"><section className="panel alert-panel"><div className="panel-heading"><div><h2>Öncelikli takip</h2><p>İşletmenin bugün kontrol etmesi gereken alanlar.</p></div><BellRing size={18} color="#087f78"/></div><div className="alert-list">{activity.map(item => { const Icon = item.icon; return <button key={item.title} onClick={() => onOpen(item.title)}><span className={`alert-icon ${item.tone}`}><Icon size={16}/></span><span><strong>{item.title}</strong><small>{item.detail}</small></span><ArrowUpRight size={15}/></button> })}</div></section><section className="panel quick-panel"><div className="panel-heading"><div><h2>Hızlı işlemler</h2><p>En sık kullanılan kayıt ekranları.</p></div><ClipboardCheck size={18} color="#087f78"/></div><div className="quick-actions"><button onClick={() => onOpen('Çalışanlar')}><Users size={18}/> Çalışan ekle</button><button onClick={() => onOpen('Stoklar')}><Boxes size={18}/> Stok kartı</button><button onClick={() => onOpen('Araçlar')}><Truck size={18}/> Varlık ekle</button><button onClick={() => onOpen('Yakıt Takibi')}><Fuel size={18}/> Yakıt kaydı</button></div></section></div>
    <div className="control-grid lower"><section className="panel analytics-panel"><div className="panel-heading"><div><h2>Operasyon aktivitesi</h2><p>Günlük üretim, sevkiyat ve görev kayıtları.</p></div><CalendarClock size={18} color="#087f78"/></div><div className="control-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7eeee"/><XAxis dataKey="name" tickLine={false} axisLine={false} tick={{fontSize:10,fill:'#789092'}}/><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{fontSize:10,fill:'#789092'}}/><Tooltip/><Bar dataKey="value" fill="#087f78" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer><span className="chart-empty-label">Henüz operasyon kaydı yok</span></div></section><section className="panel analytics-panel"><div className="panel-heading"><div><h2>İş yükü dağılımı</h2><p>Açılan kayıtların modül bazlı görünümü.</p></div><ShieldAlert size={18} color="#087f78"/></div><div className="control-donut"><ResponsiveContainer width="58%" height="100%"><PieChart><Pie data={distribution} dataKey="value" innerRadius={52} outerRadius={72} paddingAngle={4}>{distribution.map(item => <Cell key={item.name} fill={item.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="legend-list">{distribution.map(item => <span key={item.name}><i style={{ background: item.color }}/>{item.name}</span>)}</div></div></section></div>
    <section className="panel module-directory"><div className="panel-heading"><div><h2>Tüm işletme modülleri</h2><p>Her süreç için kayıt, tablo, filtre ve rapor ekranı.</p></div></div><div className="module-directory-grid">{[['Operasyonlar','Üretim & Sevkiyat',Gauge],['Bakım & Arıza','Araç Arızaları',Wrench],['Finans','Kasa & Banka',CircleDollarSign],['Satın Alma','Cari Hesaplar',ClipboardCheck],['Belgeler & Uyum','Çalışanlar',FileWarning],['Raporlar','Raporlar',BarChart3]].map(([group,label,Icon]) => <button key={String(group)} onClick={() => onOpen(String(label))}><Icon size={18}/><span><strong>{group}</strong><small>{label}</small></span><ArrowUpRight size={14}/></button>)}</div></section>
  </div>
}
