import { NextResponse } from 'next/server'
import { headers } from 'next/headers'
import { Pool } from 'pg'
import { auth } from '@/lib/auth'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const resources = ['maintenance', 'faults', 'production', 'fuel', 'tasks', 'purchases', 'documents', 'finance', 'suppliers', 'sites', 'assets', 'reports', 'summary'] as const
type Resource = typeof resources[number]
let schemaReady: Promise<void> | null = null
async function ensureSchema() {
  schemaReady ??= pool.query(`CREATE TABLE IF NOT EXISTS zirveflow_business_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL, resource TEXT NOT NULL, payload JSONB NOT NULL DEFAULT '{}'::jsonb, archived BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`).then(() => pool.query(`CREATE TABLE IF NOT EXISTS zirveflow_audit_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, details JSONB NOT NULL DEFAULT '{}'::jsonb, actor_name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`)).then(() => undefined)
  await schemaReady
}
async function sessionInfo() { const session = await auth.api.getSession({ headers: await headers() }); return session?.user ? { id: session.user.id, role: String((session.user as { role?: string }).role || 'field') } : null }
async function userId() { return (await sessionInfo())?.id ?? null }
const roleAccess: Record<string, string[]> = { field: ['field', 'admin', 'manager'], operations: ['field', 'admin', 'manager'], production: ['field', 'admin', 'manager'], fuel: ['field', 'admin', 'manager'], tasks: ['field', 'admin', 'manager'], maintenance: ['field', 'admin', 'manager'], faults: ['field', 'admin', 'manager'], assets: ['warehouse', 'admin', 'manager'], finance: ['finance', 'admin', 'manager'], suppliers: ['finance', 'admin', 'manager'], purchases: ['warehouse', 'finance', 'admin', 'manager'], documents: ['hr', 'admin', 'manager'], reports: ['finance', 'hr', 'admin', 'manager', 'field'] }
async function roleAllowed(type: string) { const session = await sessionInfo(); if (!session) return false; if (type === 'summary') return true; return (roleAccess[type] || ['admin', 'manager']).includes(session.role) }
async function audit(id: string, type: string, action: string, entityId: string, details: unknown) { await pool.query('INSERT INTO zirveflow_audit_logs (user_id, entity_type, entity_id, action, details, actor_name) VALUES ($1,$2,$3,$4,$5,$6)', [id, type, entityId, action, JSON.stringify(details || {}), 'Sistem kullanıcısı']) }
function resource(request: Request) { const value = new URL(request.url).searchParams.get('resource'); return value && resources.includes(value as Resource) ? value : null }
export async function GET(request: Request) { const id = await userId(); if (!id) return NextResponse.json({ error: 'Oturum gerekli' }, { status: 401 }); const type = resource(request); if (!type) return NextResponse.json({ error: 'Geçersiz kaynak' }, { status: 400 }); if (!(await roleAllowed(type))) return NextResponse.json({ error: 'Bu modüle erişim yetkiniz yok.' }, { status: 403 }); await ensureSchema(); if (type === 'summary') { const result = await pool.query(`SELECT resource, COUNT(*)::int AS count FROM zirveflow_business_records WHERE user_id = $1 AND archived = FALSE GROUP BY resource`, [id]); const counts = Object.fromEntries(result.rows.map(row => [row.resource, row.count])); return NextResponse.json({ counts, total: Object.values(counts).reduce((sum, value) => sum + Number(value), 0) }) } const params = new URL(request.url).searchParams; const search = params.get('search')?.trim().toLocaleLowerCase('tr-TR') || ''; const page = Math.max(1, Number(params.get('page') || 1)); const limit = Math.min(100, Math.max(1, Number(params.get('limit') || 50))); const offset = (page - 1) * limit; const result = await pool.query(`SELECT id, payload, created_at, updated_at, COUNT(*) OVER()::int AS total_count FROM zirveflow_business_records WHERE user_id = $1 AND resource = $2 AND archived = FALSE AND ($3 = '' OR LOWER(payload::text) LIKE '%' || $3 || '%') ORDER BY created_at DESC LIMIT $4 OFFSET $5`, [id, type, search, limit, offset]); const rows = result.rows.map(row => ({ id: row.id, ...row.payload, created_at: row.created_at, updated_at: row.updated_at })); return NextResponse.json({ data: rows, total: result.rows[0]?.total_count || 0, page, limit }) }
export async function POST(request: Request) { const id = await userId(); if (!id) return NextResponse.json({ error: 'Oturum gerekli' }, { status: 401 }); const type = resource(request); if (!type) return NextResponse.json({ error: 'Geçersiz kaynak' }, { status: 400 }); if (!(await roleAllowed(type))) return NextResponse.json({ error: 'Bu modüle erişim yetkiniz yok.' }, { status: 403 }); const body = await request.json().catch(() => null); if (!body || typeof body !== 'object' || Array.isArray(body)) return NextResponse.json({ error: 'Geçerli kayıt verisi gerekli' }, { status: 400 }); await ensureSchema(); const result = await pool.query('INSERT INTO zirveflow_business_records (user_id, resource, payload) VALUES ($1, $2, $3) RETURNING id, payload, created_at, updated_at', [id, type, JSON.stringify(body)]); const row = result.rows[0]; await audit(id, type, 'created', row.id, body); return NextResponse.json({ id: row.id, ...row.payload, created_at: row.created_at, updated_at: row.updated_at }, { status: 201 }) }
export async function PATCH(request: Request) { const id = await userId(); if (!id) return NextResponse.json({ error: 'Oturum gerekli' }, { status: 401 }); const type = resource(request); const recordId = new URL(request.url).searchParams.get('id'); if (!type || !recordId) return NextResponse.json({ error: 'Kaynak ve kayıt id gerekli' }, { status: 400 }); if (!(await roleAllowed(type))) return NextResponse.json({ error: 'Bu modüle erişim yetkiniz yok.' }, { status: 403 }); const body = await request.json().catch(() => null); await ensureSchema(); const result = await pool.query('UPDATE zirveflow_business_records SET payload = payload || $1::jsonb, updated_at = NOW() WHERE id = $2 AND user_id = $3 AND resource = $4 RETURNING id, payload, created_at, updated_at', [JSON.stringify(body || {}), recordId, id, type]); if (!result.rowCount) return NextResponse.json({ error: 'Kayıt bulunamadı' }, { status: 404 }); const row = result.rows[0]; await audit(id, type, 'updated', recordId, body); return NextResponse.json({ id: row.id, ...row.payload, created_at: row.created_at, updated_at: row.updated_at }) }
export async function DELETE(request: Request) { const id = await userId(); if (!id) return NextResponse.json({ error: 'Oturum gerekli' }, { status: 401 }); const type = resource(request); const recordId = new URL(request.url).searchParams.get('id'); if (!type || !recordId) return NextResponse.json({ error: 'Kaynak ve kayıt id gerekli' }, { status: 400 }); if (!(await roleAllowed(type))) return NextResponse.json({ error: 'Bu modüle erişim yetkiniz yok.' }, { status: 403 }); await ensureSchema(); const result = await pool.query('UPDATE zirveflow_business_records SET archived = TRUE, updated_at = NOW() WHERE id = $1 AND user_id = $2 AND resource = $3', [recordId, id, type]); if (!result.rowCount) return NextResponse.json({ error: 'Kayıt bulunamadı' }, { status: 404 }); await audit(id, type, 'archived', recordId, {}); return NextResponse.json({ ok: true }) }
